import type { Metadata } from 'next'
import { Ubuntu } from 'next/font/google'
import '@/styles/globals.css'
import Header from '@/components/Header'

const inter = Ubuntu({
	subsets: ['latin'],
	weight: '400'
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="w-full max-w-[940px] lg:h-[603px] sx:h-screen m-auto lg:p-4 sx:p-0 bg-white rounded-lg flex lg:flex-row sx:flex-col justify-between shadow-2xl">
					<aside className="lg:w-[30%] sx:w-full lg:h-full sx:h-40">
						<Header />
					</aside>
					<main className="lg:w-[65%] sx:w-full lg:h-full sx:h-[80%] ">{children}</main>
				</div>
			</body>
		</html>
	)
}
